### PR TITLE
Fixed boolean required (pull 96)

### PR DESCRIPTION
**Pull request by Macley-Kun**
😅

### CODE REVIEW

**Comment by synzen** [comment]
This seems to have already been done in #96

**Comment by Macley-Kun** [comment]
True, but it's for Master with the changes to only owner ID's.
I think it should be fine. You can close it if you want to update it later from web-dev.

**Comment by synzen** [comment]
Ah I see now that it is for master. Yeah, I'll hold it off til I merge dev to reduce as many merge conflicts as possible when the time comes

**Comment by Macley-Kun** [comment]
Np dude glad to be any help 👍

**Pull request closed without merging**
